//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCPDP_Parser.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UtlDetail
    {
        public UtlDetail()
        {
            this.UtlCompounds = new HashSet<UtlCompound>();
        }
        [Key]
        public int UtlDetailID { get; set; }
        public int UtlFileID { get; set; }
        public string Record_Type { get; set; }
        public string Record_Indicator { get; set; }
        public string Card_Holder_ID { get; set; }
        public string Patient_ID_Qualifier { get; set; }
        public string Patient_ID { get; set; }
        public string Patient_Last_Name { get; set; }
        public string Patient_First_Name { get; set; }
        public string Patient_Middle_Initial { get; set; }
        public string Patient_Date_Of_Birth { get; set; }
        public string Patient_Gender_Code { get; set; }
        public string Patient_Relationship_Code { get; set; }
        public string Group_ID { get; set; }
        public string Plan_Type { get; set; }
        public string Service_Provider_ID_Qualifier { get; set; }
        public string Service_Provider_ID { get; set; }
        public string Service_Provider_Chain_Code { get; set; }
        public string Prescriber_ID_Qualifier { get; set; }
        public string Prescriber_ID { get; set; }
        public string Prescriber_Last_Name { get; set; }
        public string Prescriber_First_Name { get; set; }
        public string Primary_Care_Provider_Qualifier { get; set; }
        public string Primary_Care_Provider_ID { get; set; }
        public string Primary_Care_Provider_Last_Name { get; set; }
        public string Primary_Care_Provider_First_Name { get; set; }
        public string Record_Status_Code { get; set; }
        public string Prescription_Reference_Number_Qualifier { get; set; }
        public string Prescription_Reference_Number { get; set; }
        public string Product_ID_Qualifier { get; set; }
        public string Product_ID { get; set; }
        public string Product_ID_Qualifier_Alternate { get; set; }
        public string Product_ID_Alternate { get; set; }
        public string Date_Of_Service { get; set; }
        public string Billing_Cycle_End_Date { get; set; }
        public string Place_Of_Service { get; set; }
        public string Patient_Residence { get; set; }
        public string Version_Number_Of_Claim { get; set; }
        public string Quantity_Dispensed { get; set; }
        public string Fill_Number { get; set; }
        public string Days_Supply { get; set; }
        public string DAW_Product_Selection_Code { get; set; }
        public string Fill_Number_Calculated { get; set; }
        public string Compound_Code { get; set; }
        public string Compound_Type { get; set; }
        public string Compound_Route_Of_Administration { get; set; }
        public string Route_Of_Administration { get; set; }
        public string Product_Name { get; set; }
        public string Generic_Name { get; set; }
        public string Product_Strength { get; set; }
        public string Dosage_Form_Code { get; set; }
        public string Drug_Type { get; set; }
        public string Formulary_Status { get; set; }
        public string Patient_Pay_Amount { get; set; }
        public string Ingredient_Cost_Submitted { get; set; }
        public string Net_Amount_Due { get; set; }
        public string Adjustment_Type { get; set; }
        public string Transaction_ID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }

        public virtual ICollection<UtlCompound> UtlCompounds { get; set; }
        public virtual UtlHeader UtlHeader { get; set; }
    }
}

