//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCPDP_Parser.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UtlHeader
    {
        public UtlHeader()
        {
            this.UtlDetails = new HashSet<UtlDetail>();
        }
        [Key]
        public int UtlFileID { get; set; }
        public string RecordType { get; set; }
        public string Version_Number { get; set; }
        public string Sending_Entity_ID { get; set; }
        public string Batch_Number { get; set; }
        public string Creation_Date { get; set; }
        public string Creation_Time { get; set; }
        public string Receiver_ID { get; set; }
        public string Reporting_Start_Date { get; set; }
        public string Reporting_End_Date { get; set; }
        public string File_Type { get; set; }
        public string Transmission_Action { get; set; }
        public string Submission_Number { get; set; }
        public string Total_Record_Count { get; set; }
        public string Total_Amount_Due { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }

        public virtual ICollection<UtlDetail> UtlDetails { get; set; }
    }
}

